{{- with .Values.keycloak }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
stringData:
{{- with .defaultUser }}
  KEYCLOAK_ADMIN: {{ .username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .password | quote }}
{{- end }}
{{- with $.Values.postgresql }}
  KC_DB_USERNAME: {{ .user | quote }}
  KC_DB_PASSWORD: {{ .password | quote }}
  KC_DB_URL: jdbc:postgresql://{{ .host }}:{{ .port }}/{{ $.Values.keycloak.database.name }}
{{- end }}
{{- end }}
{{- end }}
