{{- with .Values.configurator.s3 }}
{{- if not .externalSecretKey  }}
apiVersion: v1
kind: Secret
metadata:
  name: configurator-s3
stringData:
  CONFIGURATOR_S3_ACCESS_KEY: {{ quote .accessKey | default (ternary $.Values.minio.accessKey "" $.Values.minio.enabled) | quote }}
  CONFIGURATOR_S3_SECRET_KEY: {{ quote .secretKey | default (ternary $.Values.minio.secretKey "" $.Values.minio.enabled) | quote }}
{{- end }}
{{- end }}
