{{- if  .Values.running }}
{{- range $cronjob := $.Values.app.cronjobs }}
{{- if eq $cronjob.installed true }}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: phraseanet-cronjob-{{ $cronjob.name }}
  labels:
    app.kubernetes.io/name: {{ $cronjob.id }}
    app.kubernetes.io/component: cronjob
    app.kubernetes.io/instance: api
spec:
  schedule: {{ $cronjob.schedule | quote }}
  suspend: {{ $cronjob.suspend }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          {{- range $volume := $cronjob.volumes }}
          - name: phraseanet-{{ $volume.name }}
            persistentVolumeClaim:
              claimName: phraseanet-{{ $volume.name }}
          {{- end }}
          - name: phraseanet-tmp
            emptyDir:
          - name: phraseanet-logs
            emptyDir:
          - name: phraseanet-cache
            emptyDir:              
          restartPolicy: Never
          terminationGracePeriodSeconds: 60
          containers:
          - name: {{ $cronjob.name }}
            image: {{ $.Values.image.registry }}/phraseanet-worker:{{ $.Values.image.tag.phraseanet }}
            securityContext: {}
            command:
            - /bin/bash
            - -c
            - docker/phraseanet/worker/entrypoint.sh; export TERM=xterm; su app -c "{{ $cronjob.command }}"
            volumeMounts:
            {{- range $volume := $cronjob.volumes }}
            - name: phraseanet-{{ $volume.name }}
              mountPath: "/var/alchemy/Phraseanet/{{ $volume.name }}"
            {{- end }}
            env:
              - name: STACK_NAME
                value: {{ $.Values.app.stack_name | quote }}
              - name: PHP_CLI_MEMORY_LIMIT
                value: {{ $.Values.php.php_cli_memory_limit | quote }}
              - name: PHP_LOG_LEVEL
                value: {{ $.Values.php.log_level | quote }}
              - name: SESSION_CACHE_LIMITER
                value: {{ $.Values.php.session_cache_limiter | quote }}
              - name: SESSION_SAVE_HANDLER
                value: {{ $.Values.php.session_save_handler | quote }}
              - name: SESSION_SAVE_PATH
                value: {{ $.Values.php.session_save_path | quote }}
              - name: XDEBUG
                value: "0"
              - name: NEWRELIC_ENABLED
                value: {{ $.Values.php.newrelic_enabled | quote }}
              - name: NEWRELIC_LICENSE_KEY
                value: {{ $.Values.php.newrelic_licence_key | quote }}
              - name: NEWRELIC_APP_NAME
                value: {{ $.Values.php.newrelic_app_name | quote }}
              - name: LC_MESSAGES
                value: "C.UTF-8"
              - name: LC_COLLATE
                value: "C.UTF-8"
              - name: LC_IDENTIFICATION
                value: "C.UTF-8"
              - name: LANG
                value: "C.UTF-8"
              - name: LC_MEASUREMENT
                value: "C.UTF-8"
              - name: LC_CTYPE
                value: "C.UTF-8"
              - name: LC_TIME
                value: "C.UTF-8"
              - name: LC_NAME
                value: "C.UTF-8"

{{- end }}
{{- end }}
{{- end }}       
