{{- if and .Values.running .Values.app.worker.launch.subdefcreation }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phraseanet-worker-subdefcreation
spec:
  replicas: {{ .Values.app.replicas.subdefcreation.scale }}
  selector:
    matchLabels:
      app: phraseanet
      tier: worker-subdefcreation
  template:
    metadata:
      labels:
        app: phraseanet
        tier: worker-subdefcreation
    spec:
      {{- if or .Values.antiAffinity.enabled .Values.Affinity.enabled }}
      affinity:
        {{- if .Values.antiAffinity.enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "{{ .Values.antiAffinity.nodeLabel }}"
                    operator: In
                    values:
                      - "{{ .Values.antiAffinity.nodeLabelValue }}"
              topologyKey: "{{ .Values.antiAffinity.topologyKey }}"
        {{- end }}
      {{- end }}
      volumes:
      - name: phraseanet-config
        persistentVolumeClaim:
          claimName: {{ .Values.app.pvc_name.config }}
      - name: phraseanet-datas
        persistentVolumeClaim:
          claimName: {{ .Values.app.pvc_name.data }}
      - name: phraseanet-thumbnails
        persistentVolumeClaim:
          claimName: {{ .Values.app.pvc_name.thumbnails }}
      - name: phraseanet-custom
        persistentVolumeClaim:
          claimName: {{ .Values.app.pvc_name.custom }}
      - name: phraseanet-tmp
        emptyDir:
      - name: phraseanet-logs
        emptyDir:
      - name: phraseanet-cache
        emptyDir:
      {{ if .Values.image.pullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret.name }}
      {{ end }}
      containers:
      - name: phraseanet-worker
        image: {{ .Values.image.registry }}/phraseanet-worker:{{ .Values.image.tag.phraseanet }}
        imagePullPolicy: Always
        terminationMessagePolicy: FallbackToLogsOnError
        resources:
{{ toYaml .Values.app.worker.resources | indent 12 }}
        volumeMounts:
        - name: phraseanet-config
          mountPath: "/var/alchemy/Phraseanet/config"
        - name: phraseanet-datas
          mountPath: "/var/alchemy/Phraseanet/datas"
        - name: phraseanet-tmp
          mountPath: "/var/alchemy/Phraseanet/tmp"
        - name: phraseanet-logs
          mountPath: "/var/alchemy/Phraseanet/logs"
        - name: phraseanet-thumbnails
          mountPath: "/var/alchemy/Phraseanet/www/thumbnails"
        - name: phraseanet-custom
          mountPath: "/var/alchemy/Phraseanet/www/custom"
        - name: phraseanet-cache
          mountPath: "/var/alchemy/Phraseanet/cache"
{{- end }}
