{{- if .Values.configurator.executeMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: configurator-migrate-{{ .Values.configurator.executeMigration }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      {{- end }}
      volumes:
      {{- include "volumes.configs" $ | indent 6 }}
      {{- include "imagePullSecrets" $ | indent 6 }}
      containers:
      - {{- include "configurator.containerSpecs" $ | nindent 8 }}
        args:
          - 'migration:{{ .Values.configurator.executeMigration }}'
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
