{{- with .Values.novu }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: novu
stringData:
  NOVU_SECRET_KEY: {{ required "Missing novu.secretKey value" .secretKey | quote }}
---
{{- end }}
{{- end }}
