{{- if and $.Values.stack.running .Values.novu.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novu-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phrasea
      tier: novu-bridge
  template:
    metadata:
      labels:
        app: phrasea
        tier: novu-bridge
      annotations:
        {{- include "annotation.checksum.configs" $ | indent 8 }}
    spec:
      {{ include "imagePullSecrets" $ | indent 6 }}
      {{- if $.Values.nodeSelector }}
      nodeSelector: {{ toYaml $.Values.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
      containers:
      - name: novu-bridge
        image: {{ $.Values.repository.baseurl }}/ps-novu-bridge:{{ $.Values.repository.tag }}
        {{- if not (eq "latest" $.Values.repository.tag) }}
        imagePullPolicy: Always
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: NEXT_PUBLIC_NOVU_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: novu
              key: NOVU_SECRET_KEY
        - name: NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER
          valueFrom:
            configMapKeyRef:
              name: novu
              key: NOVU_APPLICATION_IDENTIFIER
        - name: NEXT_PUBLIC_NOVU_API_URL
          valueFrom:
            configMapKeyRef:
              name: novu
              key: NOVU_API_URL
        envFrom:
          - configMapRef:
              name: novu
          - secretRef:
              name: novu
{{- end }}
