{{- if .Values.expose.enabled }}
{{- with .Values.expose }}
{{- if .matomo.enabled }}
{{- with .matomo }}
apiVersion: v1
kind: Secret
metadata:
  name: matomo
stringData:
  MATOMO_AUTH_TOKEN: {{ .authToken | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
