{{- if .Values.databox.enabled }}
{{- with .Values.databox.api.config.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: databox-secrets
stringData:
  SECRETS_PUBLIC_KEY: {{ required "Missing .databox.secrets.config.secrets.publicKey value" .publicKey | quote }}
  SECRETS_SECRET_KEY: {{ required "Missing .databox.secrets.config.secrets.secretKey value" .secretKey | quote }}
---
{{- end }}
{{- end }}
